name: ETF Update

on:
  workflow_dispatch:

  schedule:
    # 台灣時間 19:13，第一次更新，不發 LINE
    - cron: "13 11 * * *"

    # 台灣時間 19:33，第二次更新並發送 LINE
    - cron: "33 11 * * *"

jobs:
  update:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: |
          pip install -r requirements.txt

      - name: Install Playwright Browser
        run: |
          playwright install chromium

      - name: Run ETF Update
        run: |
          python run_etf_update.py

      - name: Commit Excel Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add etf_holdings/

          if ! git diff --staged --quiet; then
            git commit -m "Update ETF data"
            git push
          fi

      - name: Send ETF LINE Notification
        if: github.event_name == 'schedule' && github.event.schedule == '33 11 * * *'
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
          STREAMLIT_DASHBOARD_URL: ${{ secrets.STREAMLIT_DASHBOARD_URL }}
        run: |
          python etf_line_notify.py
