name: Fund Notify

on:
  schedule:
    - cron: '13 9 * * *'
  #設定0 10 是台灣時間下午6點
  
  workflow_dispatch:

jobs:
  notify:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests beautifulsoup4 urllib3

      - name: Run notify
        env:
          LINE_TOKEN: ${{ secrets.LINE_TOKEN }}
          LINE_USER_ID: ${{ secrets.LINE_USER_ID }}
        run: |
          python fund_line_notify.py
